// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CallbackLoginData, CallbackLoginErrors, CallbackLoginResponses, ClusterLoginData, ClusterLoginErrors, ClusterLoginResponses, GetAllVisibleClusterData, GetAllVisibleClusterErrors, GetAllVisibleClusterResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get all cluster visible to the user.
 *
 * Get all cluster visible to the user,
 * if the user is not authenticated return 401,
 * if none return an empty array.
 */
export const getAllVisibleCluster = <ThrowOnError extends boolean = false>(options?: Options<GetAllVisibleClusterData, ThrowOnError>): RequestResult<GetAllVisibleClusterResponses, GetAllVisibleClusterErrors, ThrowOnError> => (options?.client ?? client).get<GetAllVisibleClusterResponses, GetAllVisibleClusterErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clusters',
    ...options
});

/**
 * Callback from the cluster's OIDC provider
 *
 * If the cluster is not found or disabled, return 404.
 */
export const callbackLogin = <ThrowOnError extends boolean = false>(options: Options<CallbackLoginData, ThrowOnError>): RequestResult<CallbackLoginResponses, CallbackLoginErrors, ThrowOnError> => (options.client ?? client).get<CallbackLoginResponses, CallbackLoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/clusters/{ns}/{cluster}/auth/callback',
    ...options
});

/**
 * Redirect to the cluster's login page
 *
 * If the cluster is not found or disabled, return 404.
 */
export const clusterLogin = <ThrowOnError extends boolean = false>(options: Options<ClusterLoginData, ThrowOnError>): RequestResult<ClusterLoginResponses, ClusterLoginErrors, ThrowOnError> => (options.client ?? client).get<ClusterLoginResponses, ClusterLoginErrors, ThrowOnError>({
    responseType: 'text',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clusters/{ns}/{cluster}/auth/login',
    ...options
});
