// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, type Options as Options2, type RequestResult, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { AuthorizeData, AuthorizeErrors, CallbackData, CallbackErrors, CallbackLoginData, CallbackLoginErrors, CallbackLoginResponses, ClusterLoginData, ClusterLoginErrors, ClusterLoginResponses, GetAllVisibleClusterData, GetAllVisibleClusterErrors, GetAllVisibleClusterResponses, JwksData, JwksErrors, JwksResponses, OauthAuthorizationServerData, OauthAuthorizationServerErrors, OauthAuthorizationServerResponses, TokenData, TokenErrors, TokenResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get all cluster visible to the user.
 *
 * Get all cluster visible to the user,
 * if the user is not authenticated return 401,
 * if none return an empty array.
 */
export const getAllVisibleCluster = <ThrowOnError extends boolean = false>(options?: Options<GetAllVisibleClusterData, ThrowOnError>): RequestResult<GetAllVisibleClusterResponses, GetAllVisibleClusterErrors, ThrowOnError> => (options?.client ?? client).get<GetAllVisibleClusterResponses, GetAllVisibleClusterErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/clusters',
    ...options
});

/**
 * OAuth 2.0 Authorization Server Metadata for the cluster's mediated OAuth Authorization Server
 *
 * Unauthenticated by nature (RFC 8414 discovery). If the cluster is not
 * found, disabled, or does not have discovery enabled, return 404.
 */
export const oauthAuthorizationServer = <ThrowOnError extends boolean = false>(options: Options<OauthAuthorizationServerData, ThrowOnError>): RequestResult<OauthAuthorizationServerResponses, OauthAuthorizationServerErrors, ThrowOnError> => (options.client ?? client).get<OauthAuthorizationServerResponses, OauthAuthorizationServerErrors, ThrowOnError>({
    responseType: 'json',
    url: '/clusters/{ns}/{cluster}/.well-known/oauth-authorization-server',
    ...options
});

/**
 * Callback from the cluster's OIDC provider
 *
 * If the cluster is not found or disabled, return 404.
 */
export const callbackLogin = <ThrowOnError extends boolean = false>(options: Options<CallbackLoginData, ThrowOnError>): RequestResult<CallbackLoginResponses, CallbackLoginErrors, ThrowOnError> => (options.client ?? client).get<CallbackLoginResponses, CallbackLoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/clusters/{ns}/{cluster}/auth/callback',
    ...options
});

/**
 * Redirect to the cluster's login page
 *
 * If the cluster is not found or disabled, return 404.
 */
export const clusterLogin = <ThrowOnError extends boolean = false>(options: Options<ClusterLoginData, ThrowOnError>): RequestResult<ClusterLoginResponses, ClusterLoginErrors, ThrowOnError> => (options.client ?? client).get<ClusterLoginResponses, ClusterLoginErrors, ThrowOnError>({
    responseType: 'text',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clusters/{ns}/{cluster}/auth/login',
    ...options
});

/**
 * Start the mediated OAuth Authorization Server flow for a cluster
 *
 * Redirects the caller's browser to the cluster's upstream OIDC provider. If
 * the cluster is not found, disabled, or discovery is not enabled, return 404.
 */
export const authorize = <ThrowOnError extends boolean = false>(options: Options<AuthorizeData, ThrowOnError>): RequestResult<unknown, AuthorizeErrors, ThrowOnError> => (options.client ?? client).get<unknown, AuthorizeErrors, ThrowOnError>({ url: '/clusters/{ns}/{cluster}/oauth/authorize', ...options });

/**
 * Callback from the cluster's upstream OIDC provider, for the mediated OAuth Authorization Server flow
 *
 * Not meant to be opened directly: the upstream provider redirects here after
 * the caller authenticates. On success, redirects to the external client's
 * own `redirect_uri` with a proxy-minted authorization code.
 */
export const callback = <ThrowOnError extends boolean = false>(options: Options<CallbackData, ThrowOnError>): RequestResult<unknown, CallbackErrors, ThrowOnError> => (options.client ?? client).get<unknown, CallbackErrors, ThrowOnError>({ url: '/clusters/{ns}/{cluster}/oauth/callback', ...options });

/**
 * The upstream identity provider's JSON Web Key Set, mirrored under the cluster's own path
 *
 * Stateless passthrough of the upstream provider's `jwks_uri`, so a caller
 * verifying a token never needs to learn or contact the upstream provider's
 * own hostname. If the cluster is not found, disabled, or does not have
 * discovery enabled, return 404.
 */
export const jwks = <ThrowOnError extends boolean = false>(options: Options<JwksData, ThrowOnError>): RequestResult<JwksResponses, JwksErrors, ThrowOnError> => (options.client ?? client).get<JwksResponses, JwksErrors, ThrowOnError>({ url: '/clusters/{ns}/{cluster}/oauth/jwks', ...options });

/**
 * Exchange a proxy-minted authorization code for the upstream tokens
 *
 * RFC 6749 §4.1.3 token endpoint. If the cluster is not found, disabled, or
 * discovery is not enabled, return 404.
 */
export const token = <ThrowOnError extends boolean = false>(options: Options<TokenData, ThrowOnError>): RequestResult<TokenResponses, TokenErrors, ThrowOnError> => (options.client ?? client).post<TokenResponses, TokenErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    url: '/clusters/{ns}/{cluster}/oauth/token',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});
