services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./tracing/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
    networks:
      default:
        ipv4_address: 10.5.0.13
  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.11.0
    networks:
      default:
        ipv4_address: 10.5.0.14
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans
  prometheus:
    image: prom/prometheus:latest
    networks:
      default:
        ipv4_address: 10.5.0.15
    volumes:
      - ./tracing/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
