from_latest_tag = false
ignore_merge_commits = false
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []
tag_prefix = "v"

[git_hooks]

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
cog check
"""

[git_hooks.pre-commit]
script = """#!/bin/sh
set -e
task recu
git add . # in case recu needed to regenerate files, add need to be done before linting
task lint
git add . # in case linting fixed anything
gitleaks git --pre-commit --redact --staged --verbose
.hooks/end-of-line.sh
.hooks/whitespace-fixer.sh
"""

[commit_types]
release = { changelog_title = "Releases" }

[changelog]
path = "CHANGELOG.md"
template = "monorepo_remote"
package_template = "package_remote"
remote = "github.com"
repository = "proxyauthK8s"
owner = "batleforc"

[bump_profiles]

[packages]
proxyauthK8S-back-crd = { path = 'libs/server/crd', bump_order = 1, public_api = true }
proxyauthK8S-back-server = { path = 'apps/server', bump_order = 1, public_api = true }
proxyauthK8S-back-trace = { path = 'libs/server/trace', bump_order = 1, public_api = true }
proxyauthK8S-back-crdgen = { path = 'apps/crdgen', bump_order = 1, public_api = true }
proxyauthK8S-back-swaggergen = { path = 'apps/swaggergen', bump_order = 1, public_api = true }
proxyauthK8S-back-api = { path = 'libs/server/api', bump_order = 1, public_api = true }
proxyauthK8S-back-controller = { path = 'libs/server/controller', bump_order = 1, public_api = true }
proxyauthK8S-back-common = { path = 'libs/server/common', bump_order = 1, public_api = true }
proxyauthK8S-back-kubectl = { path = 'apps/kubectl_proxyauth', bump_order = 1, public_api = true }
proxyauthK8S-cli-trace = { path = 'libs/cli/cli_trace', bump_order = 1, public_api = true }
proxyauthK8S-cli-client-api = { path = 'libs/cli/client_api', bump_order = 1, public_api = true }
proxyauthK8S-cli = { path = 'libs/cli/cli', bump_order = 1, public_api = true }

proxyauthK8S-front = { path = 'apps/front', bump_order = 1, public_api = true }
proxyauthK8S-front-api = { path = 'libs/front/front-api', bump_order = 1, public_api = true }
