services:
  redis:
    image: redis
    container_name: redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    environment:
      REDIS_HOST_PASSWORD: "Complexpass"
    ports:
      - "6379:6379"
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "root@example.com"
      ZO_ROOT_USER_PASSWORD: "Complexpass#123"
    ports:
      - "5080:5080"
      - "5081:5081"
  dbgate:
    image: dbgate/dbgate
    restart: always
    ports:
      - 3030:3000
    environment:
      CONNECTIONS: redis
      LABEL_redis: Redis
      SERVER_redis: redis
      PASSWORD_redis: Complexpass
      PORT_redis: 6379
      ENGINE_redis: redis@dbgate-plugin-redis
