include:
  #- .compose/compose.openobserve.yaml
  - .compose/compose.otel.yaml
  - .compose/compose.redis.yaml
  - .compose/compose.traefik.yaml
  # Choose one identity provider include (Authelia, Keycloak or Dex)
  - .compose/compose.authelia.yaml
  - .compose/compose.keycloak.yaml
  #- .compose/compose.dex.yaml

networks:
  default:
    name: proxy-auth-k8s
