include:
  - .compose/compose.otel.yaml
  - .compose/compose.redis.yaml
  - .compose/compose.traefik.yaml
  - .compose/compose.authelia.yaml

networks:
  default:
    name: talos-default
    external: true

services:
  front:
    image: proxyauthk8s/front:recette
    build:
      context: .
      dockerfile: ./deploy/build/front/Containerfile
    env_file:
      - .env
    networks:
      default:
        ipv4_address: 10.5.0.18
  back:
    image: proxyauthk8s/back:recette
    build:
      context: .
      dockerfile: ./deploy/build/back/Containerfile
    env_file:
      - .env
    environment:
      KUBECONFIG: "/kubeconfig.yaml"
    networks:
      default:
        ipv4_address: 10.5.0.19
    # mount kubeconfig.local.yaml as /kubeconfig.yaml
    volumes:
      - ./kubeconfig.local.yaml:/kubeconfig.yaml:ro
