import nx from '@nx/eslint-plugin';

export default [
  ...nx.configs['flat/base'],
  ...nx.configs['flat/typescript'],
  ...nx.configs['flat/javascript'],
  {
    ignores: [
      '**/dist',
      '**/out-tsc',
      '**/vite.config.*.timestamp*',
      '.docs/**',
    ],
  },
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx', '**/*.vue'],
    rules: {
      '@nx/enforce-module-boundaries': [
        'error',
        {
          enforceBuildableLibDependency: true,
          allow: [String.raw`^.*/eslint(\.base)?\.config\.[cm]?[jt]s$`],
          depConstraints: [
            {
              sourceTag: '*',
              onlyDependOnLibsWithTags: ['*'],
            },
          ],
        },
      ],
    },
  },
  {
    files: [
      '**/*.ts',
      '**/*.tsx',
      '**/*.cts',
      '**/*.mts',
      '**/*.js',
      '**/*.jsx',
      '**/*.cjs',
      '**/*.mjs',
    ],
    // Override or add rules here
    rules: {},
  },
  {
    // libs/front/front-api is entirely generated by @hey-api/openapi-ts
    // (see openapi-ts.config.ts). Style rules that Nx enables but the
    // generator does not target are turned off rather than patched on
    // every regeneration.
    files: ['libs/front/front-api/**/*.ts'],
    rules: {
      '@typescript-eslint/ban-ts-comment': 0,
      '@typescript-eslint/no-non-null-assertion': 0,
      '@typescript-eslint/no-explicit-any': 0,
      // Deprecated alias of no-empty-object-type, which the generator
      // already suppresses inline; Nx still enables the old rule name.
      '@typescript-eslint/no-empty-interface': 0,
      // The generator emits explicit annotations on purpose so the output
      // stays compatible with isolatedDeclarations.
      '@typescript-eslint/no-inferrable-types': 0,
    },
  },
];
