apiVersion: v1
clusters:
  - cluster:
      server: ""
    name: talos-default
contexts:
  - context:
      cluster: talos-default
      user: admin@talos-default
    name: admin@talos-default
  - context:
      cluster: talos-default
      user: admin@talos-proxy
    name: admin@talos-proxy
  - context:
      cluster: talos-default
      user: admin@talos-task
    name: admin@talos-task
current-context: admin@talos-task
kind: Config
preferences: {}
users:
  - name: admin@talos-default
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=https://authelia.k8s.localhost
          - --oidc-client-id=kube_login
          - --oidc-client-secret=insecure_secret
          - --oidc-extra-scope=groups
          - --insecure-skip-tls-verify=true
        command: kubectl
        env: null
        provideClusterInfo: false
  - name: admin@talos-proxy
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - proxyauth
          - get-token
          - -n default
          - -s https://proxyauthk8s.k8s.localhost
          - local-sso
        command: kubectl
        env: null
        provideClusterInfo: false
  - name: admin@talos-task
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1
        args:
          - cli
          - --
          - get-token
        command: task
        env: null
        provideClusterInfo: true
        interactiveMode: Never
