version: '3'

tasks:
  run:
    cmds:
      - echo "Running the main task"
      - cargo run --bin server
    desc: "Run the main task"
  gen:crds:
    silent: true
    cmds:
      - cargo run --bin crdgen
    desc: "Generate Custom Resource Definitions"
  gen:swagger:
    silent: true
    cmds:
      - cargo run --bin swaggergen
    desc: "Generate Swagger documentation"
  run:service:
    cmds:
      - echo "Running the service task"
      - command -v docker && docker compose up || true
      - command -v podman && podman compose up || true
      # check if neither docker nor podman is installed
      - |
        if ! command -v docker >/dev/null && ! command -v podman >/dev/null; then
          echo "Neither docker nor podman is installed. Please install one of them to run the service."
          exit 1
        fi
    desc: "Run the service task"