version: "3"

includes:
  talos: .taskfile/talos.yaml
  lab: .taskfile/lab.yaml
  gen: .taskfile/gen.yaml

dotenv:
  - .env

tasks:
  init:
    desc: "Initialize the project"
    silent: true
    cmds:
      - echo "Initializing the project"
      - cog install-hook -a -o
  back:
    desc: "Run the backend"
    env:
      KUBECONFIG: ./kubeconfig.local.yaml
      #OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:5081/api/default"
      #OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Basic cm9vdEBleGFtcGxlLmNvbTpDb21wbGV4cGFzcyMxMjM=,organization=default,stream-name=default"
      REDIS_URL: redis://:{{ .REDIS_PASSWORD }}@localhost:6379
    silent: true
    cmds:
      - echo "Running the backend"
      - cargo run --bin server
  back:tls:
    desc: "Run the TLS terminator"
    env:
      KUBECONFIG: ./kubeconfig.local.yaml
      REDIS_URL: redis://:{{ .REDIS_PASSWORD }}@localhost:6379
      SERVER_HTTPS: "true"
      SERVER_CERT_PATH: ".tls/cert.pem"
      SERVER_KEY_PATH: ".tls/key.pem"
      ENV: "development"
    silent: true
    cmds:
      - echo "Running the backend"
      - cargo run --bin server
  front:
    desc: "Run the frontend in development mode"
    silent: true
    cmds:
      - echo "Running the frontend in development mode"
      - yarn nx run front:dev
  front:tls:
    desc: "Run the frontend in development mode with TLS"
    silent: true
    cmds:
      - echo "Running the frontend in development mode with TLS"
      - VITE_TLS_ENABLE=true yarn nx run front:dev
  service:
    desc: "Run the service task"
    silent: true
    cmds:
      - echo "Running the service task"
      - echo "Traefik Dashboard https://traefik.k8s.localhost/dashboard/"
      # check if neither docker nor podman is installed
      - |
        if ! command -v docker >/dev/null && ! command -v podman >/dev/null; then
          echo "Neither docker nor podman is installed. Please install one of them to run the service."
          exit 1
        fi
      - command -v docker && PUID="$(id -u)" PGID="$(id -g)" docker compose up || true
      - command -v podman && PUID="$(id -u)" PGID="$(id -g)"  podman compose up || true
  service:recette:
    desc: "Run the service task in recette mode"
    silent: true
    cmds:
      - echo "Running the service task in recette mode"
      - echo "Traefik Dashboard https://traefik.k8s.localhost/dashboard/"
      # check if neither docker nor podman is installed
      - |
        if ! command -v docker >/dev/null && ! command -v podman >/dev/null; then
          echo "Neither docker nor podman is installed. Please install one of them to run the service."
          exit 1
        fi
      - command -v docker && PUID="$(id -u)" PGID="$(id -g)" MODE="recette" docker compose -f compose.recette.yaml up  || true
      - command -v podman && PUID="$(id -u)" PGID="$(id -g)" MODE="recette" podman compose -f compose.recette.yaml up || true
  init:service:
    desc: "Initialize the service task"
    silent: true
    cmds:
      - echo "Initializing the service task"
      - echo "Generating self-signed certificates for local development"
      - docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd)/.compose/authelia":/keys authelia/authelia:latest authelia crypto pair rsa generate --directory /keys

  recu:
    desc: "Run all gen jobs"
    silent: true
    cmds:
      - task gen:crds > deploy/crds.yaml
      - task gen:swagger > swagger.json
      - task gen:api-client
