version: '3'

includes:
  talos: .taskfile/talos.yaml

tasks:
  init:
    desc: "Initialize the project"
    silent: true
    cmds:
      - echo "Initializing the project"
      - cog install-hook -a -o
  run:
    desc: "Run the backend"
    env:
      KUBECONFIG: ./kubeconfig.local.yaml
    silent: true
    cmds:
      - echo "Running the backend"
      - cargo run --bin server
  gen:crds:
    desc: "Generate Custom Resource Definitions"
    silent: true
    cmds:
      - cargo run --bin crdgen
  gen:swagger:
    desc: "Generate Swagger documentation"
    silent: true
    cmds:
      - cargo run --bin swaggergen
  run:service:
    desc: "Run the service task"
    silent: true
    cmds:
      - echo "Running the service task"
      - command -v docker && docker compose up || true
      - command -v podman && podman compose up || true
      # check if neither docker nor podman is installed
      - |
        if ! command -v docker >/dev/null && ! command -v podman >/dev/null; then
          echo "Neither docker nor podman is installed. Please install one of them to run the service."
          exit 1
        fi
  recu:
    desc: "Run all gen jobs"
    silent: true
    cmds:
      - task gen:crds > deploy/crds.yaml
      - task gen:swagger > swagger.json