# Service for Backend Application
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-proxyauthk8s-back"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Release.Name }}-proxyauthk8s-back"
spec:
  selector:
    app: "{{ .Release.Name }}-proxyauthk8s-back"
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.back.port }}
      targetPort: {{ .Values.back.port }}
  type: ClusterIP
