/*
 * ProxyAuthK8S
 *
 * Reverse Proxy K8s Api.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: maxleriche.60@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetAllVisibleClusterBody : Body of the response for the get_all_visible_cluster endpoint.  Contains a list of clusters visible to the user. Will be empty if the user has no clusters visible to them.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAllVisibleClusterBody {
    #[serde(rename = "clusters")]
    pub clusters: Vec<models::VisibleCluster>,
}

impl GetAllVisibleClusterBody {
    /// Body of the response for the get_all_visible_cluster endpoint.  Contains a list of clusters visible to the user. Will be empty if the user has no clusters visible to them.
    pub fn new(clusters: Vec<models::VisibleCluster>) -> GetAllVisibleClusterBody {
        GetAllVisibleClusterBody { clusters }
    }
}
