/*
 * ProxyAuthK8S
 *
 * Reverse Proxy K8s Api
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: maxleriche.60@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAllVisibleClusterBody {
    #[serde(rename = "clusters")]
    pub clusters: Vec<models::VisibleCluster>,
}

impl GetAllVisibleClusterBody {
    pub fn new(clusters: Vec<models::VisibleCluster>) -> GetAllVisibleClusterBody {
        GetAllVisibleClusterBody {
            clusters,
        }
    }
}

