/*
 * ProxyAuthK8S
 *
 * Reverse Proxy K8s Api.
 *
 * The version of the OpenAPI document: 0.1.9
 * Contact: maxleriche.60@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OAuthAuthorizationServerMetadata : OAuth 2.0 Authorization Server Metadata (RFC 8414) for a proxied cluster.  `issuer` is this proxy's own cluster URL, and so are every other endpoint: this proxy is a full mediating Authorization Server (see [`crate::cluster::auth::oauth`]), not a pointer to the cluster's upstream OIDC provider. A caller never needs to be registered with — or even learn the hostname of — the upstream provider; the proxy is.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuthAuthorizationServerMetadata {
    #[serde(rename = "authorization_endpoint")]
    pub authorization_endpoint: String,
    #[serde(rename = "code_challenge_methods_supported")]
    pub code_challenge_methods_supported: Vec<String>,
    #[serde(rename = "grant_types_supported")]
    pub grant_types_supported: Vec<String>,
    #[serde(rename = "issuer")]
    pub issuer: String,
    #[serde(rename = "jwks_uri")]
    pub jwks_uri: String,
    #[serde(rename = "response_types_supported")]
    pub response_types_supported: Vec<String>,
    #[serde(rename = "scopes_supported")]
    pub scopes_supported: Vec<String>,
    #[serde(rename = "token_endpoint")]
    pub token_endpoint: String,
    #[serde(rename = "token_endpoint_auth_methods_supported")]
    pub token_endpoint_auth_methods_supported: Vec<String>,
}

impl OAuthAuthorizationServerMetadata {
    /// OAuth 2.0 Authorization Server Metadata (RFC 8414) for a proxied cluster.  `issuer` is this proxy's own cluster URL, and so are every other endpoint: this proxy is a full mediating Authorization Server (see [`crate::cluster::auth::oauth`]), not a pointer to the cluster's upstream OIDC provider. A caller never needs to be registered with — or even learn the hostname of — the upstream provider; the proxy is.
    pub fn new(
        authorization_endpoint: String,
        code_challenge_methods_supported: Vec<String>,
        grant_types_supported: Vec<String>,
        issuer: String,
        jwks_uri: String,
        response_types_supported: Vec<String>,
        scopes_supported: Vec<String>,
        token_endpoint: String,
        token_endpoint_auth_methods_supported: Vec<String>,
    ) -> OAuthAuthorizationServerMetadata {
        OAuthAuthorizationServerMetadata {
            authorization_endpoint,
            code_challenge_methods_supported,
            grant_types_supported,
            issuer,
            jwks_uri,
            response_types_supported,
            scopes_supported,
            token_endpoint,
            token_endpoint_auth_methods_supported,
        }
    }
}
