/*
 * ProxyAuthK8S
 *
 * Reverse Proxy K8s Api.
 *
 * The version of the OpenAPI document: 0.1.9
 * Contact: maxleriche.60@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReadinessBody : Body of the readiness probe.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReadinessBody {
    /// `ok` when Redis answered a `PING`, `unavailable` otherwise.
    #[serde(rename = "redis")]
    pub redis: String,
}

impl ReadinessBody {
    /// Body of the readiness probe.
    pub fn new(redis: String) -> ReadinessBody {
        ReadinessBody { redis }
    }
}
