/*
 * ProxyAuthK8S
 *
 * Reverse Proxy K8s Api.
 *
 * The version of the OpenAPI document: 0.1.9
 * Contact: maxleriche.60@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenErrorBody {
    #[serde(rename = "error")]
    pub error: String,
}

impl TokenErrorBody {
    pub fn new(error: String) -> TokenErrorBody {
        TokenErrorBody { error }
    }
}
