/*
 * ProxyAuthK8S
 *
 * Reverse Proxy K8s Api.
 *
 * The version of the OpenAPI document: 0.1.9
 * Contact: maxleriche.60@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenResponseBody {
    #[serde(rename = "access_token")]
    pub access_token: String,
    #[serde(
        rename = "expires_in",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_in: Option<Option<i64>>,
    #[serde(rename = "id_token")]
    pub id_token: String,
    #[serde(
        rename = "refresh_token",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub refresh_token: Option<Option<String>>,
    #[serde(rename = "scope")]
    pub scope: String,
    #[serde(rename = "token_type")]
    pub token_type: String,
}

impl TokenResponseBody {
    pub fn new(
        access_token: String,
        id_token: String,
        scope: String,
        token_type: String,
    ) -> TokenResponseBody {
        TokenResponseBody {
            access_token,
            expires_in: None,
            id_token,
            refresh_token: None,
            scope,
            token_type,
        }
    }
}
