/*
 * ProxyAuthK8S
 *
 * Reverse Proxy K8s Api
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: maxleriche.60@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VisibleCluster : Model representing a cluster visible to the user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VisibleCluster {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "is_reachable", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_reachable: Option<Option<bool>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "namespace")]
    pub namespace: String,
    #[serde(rename = "sso_enabled")]
    pub sso_enabled: bool,
}

impl VisibleCluster {
    /// Model representing a cluster visible to the user
    pub fn new(enabled: bool, name: String, namespace: String, sso_enabled: bool) -> VisibleCluster {
        VisibleCluster {
            enabled,
            is_reachable: None,
            name,
            namespace,
            sso_enabled,
        }
    }
}

