// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CallbackLoginData, CallbackLoginErrors, CallbackLoginResponses, ClusterLoginData, ClusterLoginErrors, ClusterLoginResponses, GetAllVisibleClusterData, GetAllVisibleClusterErrors, GetAllVisibleClusterResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get all cluster visible to the user
 *
 * if none return an empty array
 */
export const getAllVisibleCluster = <ThrowOnError extends boolean = false>(options?: Options<GetAllVisibleClusterData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllVisibleClusterResponses, GetAllVisibleClusterErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/clusters',
        ...options
    });
};

/**
 * Callback from the cluster's OIDC provider
 *
 * If the cluster is not found or disabled, return 404
 */
export const callbackLogin = <ThrowOnError extends boolean = false>(options: Options<CallbackLoginData, ThrowOnError>) => {
    return (options.client ?? client).get<CallbackLoginResponses, CallbackLoginErrors, ThrowOnError>({
        responseType: 'json',
        url: '/clusters/{ns}/{cluster}/auth/callback',
        ...options
    });
};

/**
 * Redirect to the cluster's login page
 *
 * If the cluster is not found or disabled, return 404
 */
export const clusterLogin = <ThrowOnError extends boolean = false>(options: Options<ClusterLoginData, ThrowOnError>) => {
    return (options.client ?? client).get<ClusterLoginResponses, ClusterLoginErrors, ThrowOnError>({
        responseType: 'text',
        url: '/clusters/{ns}/{cluster}/auth/login',
        ...options
    });
};
