// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthErrors = {
    /**
     * Internal server error.
     */
    500: unknown;
};

export type HealthResponses = {
    /**
     * Nothing
     */
    200: unknown;
};

export type BaseClusterData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/clusters/{ns}/{cluster}';
};

export type BaseClusterErrors = {
    /**
     * Internal server error.
     */
    500: unknown;
};

export type BaseClusterResponses = {
    /**
     * ATM nothing real
     */
    200: unknown;
};

export type DeleteRedirectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/clusters/{ns}/{cluster}/{path}';
};

export type DeleteRedirectErrors = {
    /**
     * Internal server error.
     */
    500: unknown;
};

export type DeleteRedirectResponses = {
    /**
     * ATM nothing real
     */
    200: unknown;
};

export type GetRedirectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/clusters/{ns}/{cluster}/{path}';
};

export type GetRedirectErrors = {
    /**
     * Internal server error.
     */
    500: unknown;
};

export type GetRedirectResponses = {
    /**
     * ATM nothing real
     */
    200: unknown;
};

export type PatchRedirectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/clusters/{ns}/{cluster}/{path}';
};

export type PatchRedirectErrors = {
    /**
     * Internal server error.
     */
    500: unknown;
};

export type PatchRedirectResponses = {
    /**
     * ATM nothing real
     */
    200: unknown;
};

export type PostRedirectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/clusters/{ns}/{cluster}/{path}';
};

export type PostRedirectErrors = {
    /**
     * Internal server error.
     */
    500: unknown;
};

export type PostRedirectResponses = {
    /**
     * ATM nothing real
     */
    200: unknown;
};

export type PutRedirectData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/clusters/{ns}/{cluster}/{path}';
};

export type PutRedirectErrors = {
    /**
     * Internal server error.
     */
    500: unknown;
};

export type PutRedirectResponses = {
    /**
     * ATM nothing real
     */
    200: unknown;
};
