// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Model representing a cluster visible to the user
 */
export type VisibleCluster = {
    enabled: boolean;
    is_reachable?: boolean | null;
    name: string;
    namespace: string;
    sso_enabled: boolean;
};

export type GetAllVisibleClusterBody = {
    clusters: Array<VisibleCluster>;
};

export type GetAllVisibleClusterData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/clusters';
};

export type GetAllVisibleClusterErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal server error.
     */
    500: unknown;
};

export type GetAllVisibleClusterResponses = {
    /**
     * ATM nothing real
     */
    200: GetAllVisibleClusterBody;
};

export type GetAllVisibleClusterResponse = GetAllVisibleClusterResponses[keyof GetAllVisibleClusterResponses];

export type ClusterLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/clusters/{ns}/{cluster}/auth/login';
};

export type ClusterLoginErrors = {
    /**
     * Cluster not found or disabled.
     */
    404: unknown;
    /**
     * Internal server error.
     */
    500: unknown;
};

export type ClusterLoginResponses = {
    /**
     * Response from remote cluster
     */
    200: unknown;
};
