// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Model representing a cluster visible to the user
 */
export type VisibleCluster = {
    enabled: boolean;
    is_reachable?: boolean | null;
    name: string;
    namespace: string;
    sso_enabled: boolean;
};

export type GetAllVisibleClusterBody = {
    clusters: Array<VisibleCluster>;
};

export type CallbackModel = {
    access_token: string;
    cluster_url: string;
    id_token: string;
    refresh_token: string;
    subject: string;
};

export type GetAllVisibleClusterData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/clusters';
};

export type GetAllVisibleClusterErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Internal server error.
     */
    500: unknown;
};

export type GetAllVisibleClusterResponses = {
    /**
     * ATM nothing real
     */
    200: GetAllVisibleClusterBody;
};

export type GetAllVisibleClusterResponse = GetAllVisibleClusterResponses[keyof GetAllVisibleClusterResponses];

export type CallbackLoginData = {
    body?: never;
    path: {
        /**
         * Namespace
         */
        ns: unknown;
        /**
         * Cluster name
         */
        cluster: unknown;
    };
    query?: never;
    url: '/clusters/{ns}/{cluster}/auth/callback';
};

export type CallbackLoginErrors = {
    /**
     * Cluster not found or disabled.
     */
    404: unknown;
    /**
     * Internal server error.
     */
    500: unknown;
};

export type CallbackLoginResponses = {
    /**
     * Response from remote cluster
     */
    200: CallbackModel;
};

export type CallbackLoginResponse = CallbackLoginResponses[keyof CallbackLoginResponses];

export type ClusterLoginData = {
    body?: never;
    path: {
        /**
         * Namespace
         */
        ns: unknown;
        /**
         * Cluster name
         */
        cluster: unknown;
    };
    query?: never;
    url: '/clusters/{ns}/{cluster}/auth/login';
};

export type ClusterLoginErrors = {
    /**
     * Cluster not found or disabled.
     */
    404: unknown;
    /**
     * Internal server error.
     */
    500: unknown;
};

export type ClusterLoginResponses = {
    /**
     * Response from remote cluster
     */
    200: string;
};

export type ClusterLoginResponse = ClusterLoginResponses[keyof ClusterLoginResponses];
