[package]
name = "crd"
version = "0.1.9"
edition = "2024"

[dependencies]
k8s-openapi = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
kube = { workspace = true }
schemars = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }

base64 = "0.23"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
