/*
 * ProxyAuthK8S
 *
 * Reverse Proxy K8s Api
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: maxleriche.60@gmail.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`callback_login`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CallbackLoginError {
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`cluster_login`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClusterLoginError {
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}


/// If the cluster is not found or disabled, return 404
pub async fn callback_login(configuration: &configuration::Configuration, ns: &str, cluster: &str, x_front_callback: Option<&str>, x_kubectl_callback: Option<&str>, code: &str, state: &str) -> Result<models::CallbackModel, Error<CallbackLoginError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_ns = ns;
    let p_path_cluster = cluster;
    let p_header_x_front_callback = x_front_callback;
    let p_header_x_kubectl_callback = x_kubectl_callback;
    let p_query_code = code;
    let p_query_state = state;

    let uri_str = format!("{}/clusters/{ns}/{cluster}/auth/callback", configuration.base_path, ns=crate::apis::urlencode(p_path_ns), cluster=crate::apis::urlencode(p_path_cluster));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("code", &p_query_code.to_string())]);
    req_builder = req_builder.query(&[("state", &p_query_state.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    match p_header_x_front_callback {
        Some(param_value) => { req_builder = req_builder.header("x-front-callback", param_value.to_string()); },
        None => { req_builder = req_builder.header("x-front-callback", ""); },
    }
    match p_header_x_kubectl_callback {
        Some(param_value) => { req_builder = req_builder.header("x-kubectl-callback", param_value.to_string()); },
        None => { req_builder = req_builder.header("x-kubectl-callback", ""); },
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CallbackModel`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CallbackModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CallbackLoginError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// If the cluster is not found or disabled, return 404
pub async fn cluster_login(configuration: &configuration::Configuration, ns: &str, cluster: &str, x_front_callback: Option<&str>, x_kubectl_callback: Option<&str>) -> Result<String, Error<ClusterLoginError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_ns = ns;
    let p_path_cluster = cluster;
    let p_header_x_front_callback = x_front_callback;
    let p_header_x_kubectl_callback = x_kubectl_callback;

    let uri_str = format!("{}/clusters/{ns}/{cluster}/auth/login", configuration.base_path, ns=crate::apis::urlencode(p_path_ns), cluster=crate::apis::urlencode(p_path_cluster));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    match p_header_x_front_callback {
        Some(param_value) => { req_builder = req_builder.header("x-front-callback", param_value.to_string()); },
        None => { req_builder = req_builder.header("x-front-callback", ""); },
    }
    match p_header_x_kubectl_callback {
        Some(param_value) => { req_builder = req_builder.header("x-kubectl-callback", param_value.to_string()); },
        None => { req_builder = req_builder.header("x-kubectl-callback", ""); },
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Ok(content),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClusterLoginError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

