[package]
name = "virtual_api"
version = "0.1.9"
edition = "2024"

[dependencies]
serde_json = { workspace = true }
tracing = { workspace = true }
k8s-openapi = { workspace = true }

crd = { path = "../crd", version = "0.1.9" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
