/*
 * ProxyAuthK8S
 *
 * Reverse Proxy K8s Api
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: maxleriche.60@gmail.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`delete_redirect`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteRedirectError {
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_redirect`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetRedirectError {
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`patch_redirect`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PatchRedirectError {
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_redirect`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostRedirectError {
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`put_redirect`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PutRedirectError {
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}


/// Redirect to the cluster if exists
pub async fn delete_redirect(configuration: &configuration::Configuration, ns: &str, cluster: &str, path: &str) -> Result<(), Error<DeleteRedirectError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_ns = ns;
    let p_path_cluster = cluster;
    let p_path_path = path;

    let uri_str = format!("{}/clusters/{ns}/{cluster}/{path}", configuration.base_path, ns=crate::apis::urlencode(p_path_ns), cluster=crate::apis::urlencode(p_path_cluster), path=crate::apis::urlencode(p_path_path));
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteRedirectError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Redirect to the cluster if exists
pub async fn get_redirect(configuration: &configuration::Configuration, ns: &str, cluster: &str, path: &str) -> Result<(), Error<GetRedirectError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_ns = ns;
    let p_path_cluster = cluster;
    let p_path_path = path;

    let uri_str = format!("{}/clusters/{ns}/{cluster}/{path}", configuration.base_path, ns=crate::apis::urlencode(p_path_ns), cluster=crate::apis::urlencode(p_path_cluster), path=crate::apis::urlencode(p_path_path));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<GetRedirectError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Redirect to the cluster if exists
pub async fn patch_redirect(configuration: &configuration::Configuration, ns: &str, cluster: &str, path: &str) -> Result<(), Error<PatchRedirectError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_ns = ns;
    let p_path_cluster = cluster;
    let p_path_path = path;

    let uri_str = format!("{}/clusters/{ns}/{cluster}/{path}", configuration.base_path, ns=crate::apis::urlencode(p_path_ns), cluster=crate::apis::urlencode(p_path_cluster), path=crate::apis::urlencode(p_path_path));
    let mut req_builder = configuration.client.request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<PatchRedirectError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Redirect to the cluster if exists
pub async fn post_redirect(configuration: &configuration::Configuration, ns: &str, cluster: &str, path: &str) -> Result<(), Error<PostRedirectError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_ns = ns;
    let p_path_cluster = cluster;
    let p_path_path = path;

    let uri_str = format!("{}/clusters/{ns}/{cluster}/{path}", configuration.base_path, ns=crate::apis::urlencode(p_path_ns), cluster=crate::apis::urlencode(p_path_cluster), path=crate::apis::urlencode(p_path_path));
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<PostRedirectError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Redirect to the cluster if exists
pub async fn put_redirect(configuration: &configuration::Configuration, ns: &str, cluster: &str, path: &str) -> Result<(), Error<PutRedirectError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_ns = ns;
    let p_path_cluster = cluster;
    let p_path_path = path;

    let uri_str = format!("{}/clusters/{ns}/{cluster}/{path}", configuration.base_path, ns=crate::apis::urlencode(p_path_ns), cluster=crate::apis::urlencode(p_path_cluster), path=crate::apis::urlencode(p_path_path));
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<PutRedirectError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

