name: 🦀 Rust dependency audit
on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  schedule:
    - cron: "50 23 * * *"
permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      checks: write
      contents: read
      security-events: write
      actions: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: rustsec/audit-check@dd51754d4e59da7395a4cd9b593f0ff2d61a9b95 # v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
